{include file="header.phtml"}
    <div class="main-container">
        <div class="main clearfix">
            <div id="zmap" class="exploremap">
                <div class="map-info">
                    <div class="header">
                        <a href="#" class="btn-close"><i class="ion-ios7-close-empty"></i></a>
                    </div>
                    <div class="content">
                        <div class="basic-info">
                            <h1 class="info-title">{$layer.title}</h1>
                            <div class="info-description">
                                {$layer.abstract}
                            </div>
                            <div class="info-meta">
                                <div class="author">Pembuat: {$layer.contributor}</div>
                                <div class="view">Dilihat: <span class="value">{$layer.num_view}</span> kali</div>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    {literal}
                    var singleLayer = {
                        title : {/literal}'{$layer.title}'{literal},
                        type  : 'wms',
                        wms   : {
                            url        : {/literal}'{$layer.url}'{literal},
                            params     : {{/literal}'LAYERS': '{$layer.layer}'{literal}}
                        },
                        extent : {/literal}{$layer.extent|@json_encode}{literal}
                    }
                    {/literal}
                </script>
            </div>
        </div>
    </div>
    <!--  //MAIN -->

{include file="footer.phtml"}