{include file="header.phtml"}
        <div class="main-container">
            <div class="main clearfix">


                <section class="primary padding clearfix">
                    <div class="panel">
                        <header class="panel-header clearfix">
                            <h2 class="detail-title">Edit Dokumen</h2>
                        </header>
                        <div class="panel-content clearfix">
                            <div class="upload">
                                <form action="{$_URL}/member/dokumen/edit/{$id_dokumen}" method="post" enctype='multipart/form-data' class="general-form">
                                    {*<p class="alert success">Well done! You successfully read this important alert message.</p>
                                    <p class="alert info">Heads up! This alert needs your attention, but it is not super important.</p>
                                    <p class="alert warning">Warning! Best check yo self, you're not looking too good.</p>
                                    <p class="alert danger">Oh snap! Change a few things up and try submitting again.</p>*}
                                    <p>
                                        <label>Judul</label>
                                        <input type="text" name="judul" class="input-text" value="{$document.judul}">
                                    </p>
                                    <p>
                                        <label>Abstrak</label>
                                        <textarea name="abstract" class="input-text" rows="5">{$document.konten}</textarea>
                                    </p>
                                    <p>
                                        <label>Tautan Peta</label>
                                        <span class="select-options">
                                            <select name="category">
                                                {foreach $categories as $cat}
                                                <option value="{$cat.value}"{if $document.id_kategori == $cat.value} selected="selected"{/if}>{$cat.name}</option>
                                                {/foreach}
                                            </select>
                                            <i class="arrow ion-chevron-down"></i>
                                        </span>
                                    </p>
                                    <p class="action">
                                        <button type="submit" class="btn primary">Simpan</button>
                                        <input type="hidden" name="submit" value="1">
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>

                <aside class="secondary padding clearfix">

                </aside>
            </div>
        </div>
        <!--  //MAIN -->
{include file="footer.phtml"}