{include file="header.phtml"}
    <div class="main-container">
        <div class="main clearfix">
            <div id="zmap" data-edit="true" data-hapus="true" class="exploremap" data-action="{$_URL}/member/peta/edit/{$url_segment}">
                <div class="map-info">
                    <div class="header">
                        <a href="#" class="btn-close"><i class="ion-ios7-close-empty"></i></a>
                    </div>
                    <div class="content basic-info-form">
                        <div class="basic-info basic-info-display">
                            <h1 class="info-title">{$map_data.title}</h1>
                            <div class="info-description">
                                {$map_data.abstract}
                            </div>
                            <div class="info-meta">
                                <div class="author">Pembuat: {$map_data.contributor}</div>
                                <div class="view">Dilihat: <span class="value">{$map_data.num_view}</span> kali</div>
                            </div>
                        </div>
                        <div class="basic-info general-form basic-info-edit">
                            <p>
                                <label>Judul</label>
                                <input type="text" id="txt-judul" name="judul" value="{$map_data.title}" class="input-text">
                            </p>
                            <p>
                                <label>Abstrak</label>
                                <textarea name="abstract" id="txt-absctract" class="input-text" rows="5">{$map_data.abstract}</textarea>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--  //MAIN -->
<script type="text/javascript">
    var map_data = {$map_data|@json_encode};
</script>

{include file="footer.phtml"}