{include file="header.phtml"}
    <div class="main-container">
        <div class="main clearfix">
            <div id="zmap" class="exploremap edit-active" data-simpan="true" data-action="{$_URL}/member/peta/upload">
                <div class="map-info">
                    <div class="header">
                        <a href="#" class="btn-close"><i class="ion-ios7-close-empty"></i></a>
                    </div>
                    <div class="content">
                        <div class="basic-info general-form basic-info-edit">
                            <p>
                                <label>Judul</label>
                                <input type="text" id="txt-judul" name="judul" class="input-text">
                            </p>
                            <p>
                                <label>Abstrak</label>
                                <textarea name="abstract" id="txt-absctract" class="input-text" rows="5"></textarea>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--  //MAIN -->

{include file="footer.phtml"}